### PR TITLE
fix: Update hyprland package to 0.4.0-alpha.1

### LINKED ISSUE #153: bug: randr plugin (and anyrun as a whole) panics on Hyprland 0.40.0
**Steps to reproduce**:
- install and run Hyprland >0.40.0
- open anyrun

**Expected behavior**:
- anyrun opens without issues

**Actual behavior**:
- anyrun panics: 
  ```
  thread '<unnamed>' panicked at 'A error occured while parsing the output from the hypr socket: IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', /home/peppidesu/.cargo/registry/src/github.com-1ecc6299db9ec823/hyprland-0.3.9/src/data/regular.rs:31:19
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', plugins/randr/src/lib.rs:106:1
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', plugins/randr/src/lib.rs:37:1

  file:plugins/randr/src/lib.rs
  line:37
  Attempted to panic across the ffi boundary.
  Aborting to handle the panic...
  ```

**Reason**:
Hyprland has moved the hyprland socket from `/tmp/hypr` to `$XDG_RUNTIME_DIR` in 0.40.0. This change has been merged into `hyprland-rs:master`, but are not yet included in the latest release.

**Solution**:
Either:
- wait for the next release of `hyprland-rs`, and change the package version in `plugins/randr/Cargo.toml`.
- temporarily grab the package from the master branch: 
  ```toml
  hyprland = { git = "https://github.com/hyprland-community/hyprland-rs", branch = "master" }
  ```

### PR DESCRIPTION
**Pull request by peppidesu**
Fixes #153

### CODE REVIEW

**Comment by TheRealGramdalf** [comment]
This could technically use `0.40.0-alpha.2` now (though the changes are minimal, mostly deps and docs stuff). Is there anything preventing this from being merged? Anyrun is mostly unusable (read: requires symlink from `/tmp/hypr` to `/run/user/<UID>/hypr` to work, which isn't great on a multi user system) on Hyprland v0.40.0.x, so having this merged would be quite nice.

**Comment by TheRealGramdalf** [comment]
As a temporary workaround (provided you use NixOS with flakes), I can set my `inputs` to use this PR as the branch:
```nix
    anyrun = {
      url = "github:anyrun-org/anyrun/9e14b5946e413b87efc697946b3983d5244a1714";
      inputs.nixpkgs.follows = "nixpkgs";
    };
```

This will pin anyrun to the version associated with the PR, at the cost of no longer following `master` for the latest features etc.

**Comment by kmate** [comment]
Never mind, the cargo package is alpha 2.... I looked at the wrong version, sorry.

**Comment by NotAShelf** [comment]
Sorry for the delay, I was waiting for upstream to publish a stable release.

Hyprland-rs just got an update, if it turns out to be stable I will update the crate today.

**Comment by TheRealGramdalf** [comment]
It is technically marked as alpha 3, but If it helps I've been using alpha 2 for several months now and haven't noticed any issues. That does mean I also haven't been keeping up to date with anyrun updates (I used the branch directly, not a patch), but `9e14b5946e413b87efc697946b3983d5244a1714` seems to be fine.

**Comment by NotAShelf** [comment]
@peppidesu do you think you could bump this to alpha 3? I can merge it then.

**Comment by peppidesu** [comment]
Yeah, sorry for inactivity. I'll get to it tomorrow

**Pull request closed without merging**
